#!/usr/bin/env python3
"""Validate stage completion status reports generated by stages-action runtime."""

from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path

MARKDOWN_ARTIFACTS_CONFIG = (
    Path(__file__).resolve().parents[2] / "artifacts" / "config" / "markdown-artifacts.env"
)


def _load_stage_completion_filenames() -> tuple[str, tuple[str, ...]]:
    config: dict[str, str] = {}
    for raw_line in MARKDOWN_ARTIFACTS_CONFIG.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        config[key.strip()] = value.strip()

    canonical = config.get("STAGE_COMPLETION_FILENAME", "stage-completion-status.md")
    legacy = tuple(
        part.strip()
        for part in config.get("STAGE_COMPLETION_LEGACY_FILENAMES", "").split(",")
        if part.strip()
    )
    return canonical, legacy


STAGE_COMPLETION_FILENAME, STAGE_COMPLETION_LEGACY_FILENAMES = (
    _load_stage_completion_filenames()
)

REQUIRED_LINES = (
    "- dry_run_mode:",
    "- agile_coach_first: true",
    "- progress_steps:",
    "- pr_open_total:",
    "- pr_merged_total:",
    "- pr_approved_merged_total:",
    "- powerpoint_required:",
    "- powerpoint_post_gate_executed:",
    "- powerpoint_wiki_exists:",
    "- powerpoint_source_exists:",
    "- powerpoint_hash_match:",
    "## PR Status by Ticket",
    "## Completed Successfully",
    "## Approval Links Requiring Re-run",
    "## Not Completed and Why",
    "## Recommendations",
)


def _repo_root(default: str) -> Path:
    return Path(default).resolve()


def _latest_report_path(repo_root: Path, stage: str) -> Path:
    review_root = repo_root / ".digital-artifacts" / "60-review"
    candidates = sorted(
        path
        for pattern in (
            STAGE_COMPLETION_FILENAME,
            *STAGE_COMPLETION_LEGACY_FILENAMES,
        )
        for path in review_root.glob(f"*/{stage}/{pattern}")
        if path.is_file()
    )
    candidates = sorted(
        candidates,
        key=lambda path: path.as_posix(),
    )
    if not candidates:
        raise FileNotFoundError(
            f"No stage completion report found for stage '{stage}' under {review_root}",
        )
    return candidates[-1]


def latest_report_path(repo_root: Path, stage: str) -> Path:
    """Return newest stage completion report path for a given stage."""
    return _latest_report_path(repo_root, stage)


def _extract_generated_at(lines: list[str]) -> datetime:
    prefix = "- generated_at: "
    for line in lines:
        if line.startswith(prefix):
            stamp = line[len(prefix) :].strip()
            parsed = datetime.fromisoformat(stamp.replace("Z", "+00:00"))
            if parsed.tzinfo is None:
                parsed = parsed.replace(tzinfo=timezone.utc)
            return parsed.astimezone(timezone.utc)
    raise ValueError("Missing '- generated_at:' line")


def _extract_value(lines: list[str], key: str) -> str:
    prefix = f"- {key}: "
    for line in lines:
        if line.startswith(prefix):
            return line[len(prefix) :].strip().strip('"')
    raise ValueError(f"Missing '- {key}:' line")


def validate_report(report_path: Path, stage: str, max_age_hours: int) -> None:
    if not report_path.exists():
        raise FileNotFoundError(f"Missing report file: {report_path}")

    content = report_path.read_text(encoding="utf-8")
    lines = content.splitlines()

    expected_title = f"# Stage Completion Status ({stage})"
    if not lines or lines[0].strip() != expected_title:
        raise ValueError(
            f"Unexpected report title in {report_path}: expected '{expected_title}'",
        )

    for marker in REQUIRED_LINES:
        if marker not in content:
            raise ValueError(f"Missing required marker '{marker}' in {report_path}")

    generated_at = _extract_generated_at(lines)
    oldest_allowed = datetime.now(timezone.utc) - timedelta(hours=max_age_hours)
    if generated_at < oldest_allowed:
        raise ValueError(
            f"Report is stale: generated_at={generated_at.isoformat()} older than {max_age_hours}h",
        )

    # Project stage has a mandatory post-run PowerPoint synchronization gate.
    if stage == "project":
        dry_run_mode = _extract_value(lines, "dry_run_mode")
        ppt_required = _extract_value(lines, "powerpoint_required")
        ppt_executed = _extract_value(lines, "powerpoint_post_gate_executed")
        ppt_wiki_exists = _extract_value(lines, "powerpoint_wiki_exists")
        ppt_source_exists = _extract_value(lines, "powerpoint_source_exists")
        ppt_hash_match = _extract_value(lines, "powerpoint_hash_match")

        if ppt_required != "true":
            raise ValueError("Project stage report must declare '- powerpoint_required: true'")
        if dry_run_mode != "true":
            if ppt_executed != "true":
                raise ValueError(
                    "Project stage report missing PowerPoint post-gate execution proof",
                )
            if ppt_wiki_exists != "true" or ppt_source_exists != "true":
                raise ValueError("Project stage report indicates missing PowerPoint artifacts")
            if ppt_hash_match != "true":
                raise ValueError("Project stage report indicates PowerPoint hash mismatch")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repository root")
    parser.add_argument("--stage", default="project", help="Stage name")
    parser.add_argument("--report-path", default="", help="Explicit report path override")
    parser.add_argument(
        "--max-age-hours",
        type=int,
        default=24,
        help="Maximum report age in hours before gate fails",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    repo_root = _repo_root(args.repo_root)
    report_path = (
        Path(args.report_path).resolve()
        if args.report_path
        else latest_report_path(repo_root, args.stage)
    )

    validate_report(report_path, args.stage, args.max_age_hours)
    print(f"stage-completion-gate: ok report={report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
